[workspace]
members = ["day1", "day2", "day3", "day4", "day6", "day7", "day8", "day9", "day10", "day11", "day14", "day15", "meta"]

[workspace.dependencies]
aoc-traits = { git = "https://github.com/dkales/adventofcode2023-leaderboard", rev = "ac544663758c2dca2ee892fd7ab59419999350dc" }
